version: "3.8"
services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - appnet

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - appnet
    volumes:
      - grafana-data:/var/lib/grafana

networks:
  appnet:
    driver: bridge

volumes:
  grafana-data:
